apiVersion: v1
kind: Secret
metadata:
  name: s3-bucket-owner
  namespace: s3-provisioner
type: Opaque
data:
  AWS_ACCESS_KEY_ID: *base64 encoded value*
  AWS_SECRET_ACCESS_KEY: *base64 encoded value*